[project]
name = "azr-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "geopy>=2.4.1",
    "httpx[cli]>=0.28.1",
    "markitdown>=0.1.2",
    "mcp[cli]>=1.10.1",
]
